[package]
name = "picocaml"
version = "0.1.0"
edition = "2024"

[lib]
name = "picocaml"
path = "src/libs/lib.rs"

[dependencies]
anyhow = "1.0.100"
thiserror = "2.0.16"
nanoid = "0.4.0"
rustyline = "17.0.1"
